import type { Transition } from 'motion/react'

/** Framer's default ease-in-out curve. */
export const framerEase = [0.44, 0, 0.56, 1] as const

/**
 * Every timing on the site, taken from the live Framer bundles.
 * Components pick one by name; hover/press springs are mirrored in
 * src/styles/motion.css (generated by scripts/spring-easings.mjs).
 */
export const transitions = {
  /** Framer's default 0.4s spring: menus, accordion, filters, layout changes. */
  base: { type: 'spring', duration: 0.4, bounce: 0.2 },
  /** Fast, no overshoot: cursor follow, hovers. */
  snappy: { type: 'spring', stiffness: 500, damping: 60, mass: 1 },
  /** Heavy reveal for images and text blocks on scroll. */
  reveal: { type: 'spring', stiffness: 160, damping: 55, mass: 2, delay: 0.1 },
  /** Slow reveal for project tiles; also the scroll-indicator travel. */
  tile: { type: 'spring', duration: 1.2, bounce: 0.2 },
  /** Mobile menu open/close. */
  menu: { type: 'spring', stiffness: 300, damping: 60, mass: 2 },
  /** About carousel slides. */
  carousel: { type: 'spring', stiffness: 200, damping: 20, mass: 1 },
  /** Per-word reveal of the Home statement (staggered by 0.075s). */
  word: { type: 'spring', duration: 0.4, bounce: 0, restDelta: 0.001 },
  /** Small tweens: form button states, scroll-indicator fade. */
  fast: { type: 'tween', duration: 0.2, ease: framerEase },
  fade: { type: 'tween', duration: 0.3, ease: framerEase },
} satisfies Record<string, Transition>

export type TransitionName = keyof typeof transitions

/** Scroll reveals start just above zero opacity (like Framer), so Chrome still counts them for LCP. */
export const revealFrom = { opacity: 0.001, y: 30 }
export const revealTo = { opacity: 1, y: 0 }
